# Generated by Django 5.1.3 on 2024-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_influencerprofile_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='price',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='max_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
