# Generated by Django 5.1.3 on 2024-11-25 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_influencerprofile_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerprofile',
            name='contents',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='method',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='post_account',
            field=models.ForeignKey(blank=True, db_column='email_account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
