# Generated by Django 5.1.3 on 2024-11-25 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_influencerprofile_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiserprofile',
            name='address',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='advertiserprofile',
            name='post_account',
            field=models.ForeignKey(blank=True, db_column='email_account', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
