# Generated by Django 5.1 on 2024-11-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_nickname_alter_profile_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.CharField(max_length=128),
        ),
    ]
