# Generated by Django 5.1.3 on 2024-11-26 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(default='product.svg', upload_to='advertisement/')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('sns', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('youtube', 'Youtube'), ('other', 'Other')], max_length=50)),
                ('method', models.CharField(blank=True, max_length=128)),
                ('field', models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('food', 'Food'), ('health', 'Health'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(default='description of the product')),
                ('min_budget', models.PositiveIntegerField(default=0)),
                ('max_budget', models.PositiveIntegerField(default=0)),
                ('detail_1', models.ImageField(default='product.svg', upload_to='advertisement/')),
                ('detail_2', models.ImageField(default='product.svg', upload_to='advertisement/')),
                ('post_account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
