# Generated by Django 5.1.3 on 2024-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_advertisement_post_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='field',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('food', 'Food'), ('health', 'Health'), ('other', 'Other')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
