# Generated by Django 5.1.3 on 2024-11-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='field',
            field=models.CharField(blank=True, choices=[('fashion', 'Fashion'), ('food', 'Food'), ('health', 'Health'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
