# Generated by Django 5.1.3 on 2024-11-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="content",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="profile",
            name="max_budget",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="min_budget",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="platform",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="profile",
            name="text_box",
            field=models.CharField(default="", max_length=512),
        ),
    ]
