# Generated by Django 5.1.3 on 2024-11-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0005_profile_content_profile_max_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="urls",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="img",
            field=models.ImageField(default="product.svg", upload_to="profile/"),
        ),
    ]
