# Generated by Django 5.1.3 on 2024-11-22 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0002_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="username",
        ),
    ]
