# Generated by Django 5.1.3 on 2024-11-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0003_rename_name_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.CharField(default="", max_length=128),
        ),
    ]
