# Generated by Django 5.1.3 on 2024-11-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0004_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
