# Generated by Django 5.1.3 on 2024-11-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0005_user_is_staff_user_is_superuser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
