# Generated by Django 5.1.3 on 2024-11-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0008_rename_username_token_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(default="Influencer", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name="Token",
        ),
    ]
