# Generated by Django 5.1.3 on 2024-11-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0009_remove_user_email_user_position_alter_user_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
    ]
