# Generated by Django 5.1.3 on 2024-11-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0010_remove_user_is_active_remove_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="logg.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=128),
        ),
    ]
