# Generated by Django 5.1.3 on 2024-11-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0011_alter_profile_user_alter_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
