# Generated by Django 5.1.3 on 2024-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0012_user_is_active_user_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
