# Generated by Django 5.1.3 on 2024-11-25 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="user",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
