# Generated by Django 5.1.3 on 2024-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logg", "0002_advertisement_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="category",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="sns",
            field=models.CharField(default="", max_length=128),
        ),
    ]
