# Generated by Django 5.1.3 on 2024-11-23 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
