# Generated by Django 5.1.3 on 2024-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_influencerprofile_id_influencerprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
